//
//  File.swift
//  twitterClone
//
//  Created by KH on 19/04/2023.
//

import Foundation

struct Tweet: Codable {
    var id = UUID().uuidString //the random unique id is generated by defualt
    let author: TwitterUser
    let authorID: String
    let tweetContent: String
    var likesCount: Int
    var likers: [String]
    let isReply: Bool
    let ParentReference: String?
}

